name: Build ClickHouse on Kylin OS (ARMv8) and Push to GHCR

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
        with:
          platforms: arm64

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_TOKEN }}

      - name: Build and Push ClickHouse
        uses: docker/build-push-action@v2
        with:
          context: .
          file: Dockerfile.kylin-armv8
          platforms: linux/arm64
          push: true  # 设置为 true，以便在构建完成后自动推送镜像到 GHCR
          tags: ghcr.io/cryzlasm/clickhouse:kylin-armv8
