name: Build ClickHouse on Kylin OS (ARMv8) and Push to GHCR

on:
  push:
    branches:
      - main
      - master
  pull_request:
    branches:
      - main
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
        with:
          platforms: arm64

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_TOKEN }}

      - name: Build and Push ClickHouse
        uses: docker/build-push-action@v2
        with:
          context: .
          file: Dockerfile.kylin-armv8
          platforms: linux/arm64
          push: true
          tags: |
            ghcr.io/cryzlasm/clickhouse:v23.8.2.7-lts-kylin-armv8
            ghcr.io/cryzlasm/clickhouse:latest-kylin-armv8