name: Build ClickHouse on Kylin OS (ARMv8) and Push to GHCR

on:
  push:
    branches:
      - main  # 监控 main 分支
      - master  # 新增：监控 master 分支
  pull_request:
    branches:
      - main  # 监控针对 main 分支的拉取请求
      - master  # 新增：监控针对 master 分支的拉取请求

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
        with:
          platforms: arm64

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_TOKEN }}

      - name: Build and Push ClickHouse
        uses: docker/build-push-action@v2
        with:
          context: .
          file: Dockerfile.kylin-armv8
          platforms: linux/arm64
          push: true  # 设置为 true，以便在构建完成后自动推送镜像到 GHCR
          tags: |
            ghcr.io/myusername/clickhouse:v23.8.2.7-lts-kylin-armv8  # 包含版本号的标签
            ghcr.io/myusername/clickhouse:latest-kylin-armv8        # 可选：latest 标签